apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }    
...
    }
    test:53 {
            errors
            cache 30
            forward . 192.168.49.2
    }
kind: ConfigMap
metadata:
...
